# Generated by Django 4.2.6 on 2023-10-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('card_number', models.CharField(max_length=20)),
                ('expiry_date', models.DateField()),
                ('cvv', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.TextField()),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.TextField()),
                ('country', models.TextField()),
                ('city', models.TextField()),
                ('address', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='toy',
            name='colors',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='toy',
            name='delivery_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='toy',
            name='details',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='toy',
            name='material',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='toy',
            name='out_of_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='toy',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='toy',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='toy',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
